# ФИО выполнившего работу студента, номер группы и номер зачетной книжки
---
ФИО: Мяделец Андрей Алексеевич;  
Группа: КИ19-07б;  
Номер зачетной книжки: 031941203.

# Знакомство с библиотекой NumPy
---
NumPy — библиотека для работы с многомерными массивами и математических вычислений различного рода.  
NumPy можно рассматривать как некую альтернативу MATLAB.  
   
[Документация NumPy](https://numpy.org/doc/stable/reference/index.html)

**Импорт библиотеки NumPy:**

In [2]:
import numpy as np

**Создание одномерного массива:**

In [3]:
array_1D = np.array([1, 0, 2, 3])

**Вывод массива для ознакомления:**

In [ ]:
array_1D

**Создание двумерного массива:**


In [ ]:
array_2D = np.array([[1, 0, 2], [3, 4, 5], [6, 8, 7], [12, 22, 9]])
array_2D

**Просмотр типа данных элементов массива:**

In [ ]:
array_2D.dtype

**Тип данных можно задать при создании массива:**

In [ ]:
array_int32 = np.array([1], dtype = np.float)
print(array_int32.dtype, "- тип данных")
print(array_int32, "- значение переменных массива")

**Вывод размерности массива:**

In [ ]:
print(array_1D.shape, "- количество элементов одномерного массива")
print(array_2D.shape, "- количество строк и столбцов двумерного массива")

print(array_1D.size, "- количество элементов одномерного массива")
print(array_2D.size, "- количество элементов двумерно массива")

**Варианты автоматического заполнения массивов:**

In [ ]:
np.ones((2, 2))

In [ ]:
np.zeros((2, 3))

In [ ]:
np.eye(4)

In [ ]:
np.random.random((2, 4))

In [ ]:
np.full((2, 2), 5)

In [ ]:
np.arange(15)

**Обращение к элементу массива по его индексу:**  
*(индексация начинается с нуля)*

In [ ]:
print(array_1D)
array_1D[1]

In [ ]:
print(array_2D)
array_2D[1, 2]

In [ ]:
print(array_2D[:, :])
array_2D[:2, :3]

In [ ]:
np.argmax(array_1D) # индекс максимального элемента массива
array_1D[np.argmax(array_1D)]

**Просмотр элементов массива, удовлетворяющих условию:**

In [ ]:
array_2D > 5

In [ ]:
array_2D[array_2D > 5]

**Изменение размерности матрицы:**

In [ ]:
print(array_2D)
array_2D.flatten()

In [ ]:
print(array_2D)
array_2D.reshape(6,2)

In [ ]:
# Метод resize() изменяет размерность массива и перезаписывает его
print(array_2D)
array_2D.resize(2, 6)
array_2D

**Арифметические действия с массивами:**

In [ ]:
a = np.array([1, 2])
b = np.array([2, 3])

In [ ]:
# сложение
print(a + b, '\n')
print(np.add(a, b))

In [ ]:
# вычитание
print(a - b, '\n')
print(np.subtract(a, b))

In [ ]:
# деление
print(a / b, '\n')
print(np.divide(a, b))

In [ ]:
# поэлементное умножение
print(a * b, '\n')
print(np.multiply(a, b))

**Скалярное произведение векторов, умножение матриц:**

In [ ]:
a = np.array([2, 3])
b = np.array([[4], [5]])

In [ ]:
print(np.dot(a, b), '\n')
print(a @ b)

In [ ]:
print(np.dot(a, 3), '\n')
print(a * 3)

**Суммирование элементов массива:**

In [ ]:
a = np.array([1, 2, 3])
np.sum(a)

In [ ]:
a = a * 2.0 # изменение типа элементов массива на float
print(a)
np.sum(a, dtype = np.int64) # суммирование элементов массива и приведение к типу int

In [ ]:
# сумма элементов по столбцам
a = np.array([[4, 5, 6], [2, 3, 4]])
np.sum(a, axis = 0)

In [ ]:
# сумма элементов по строкам
np.sum(a, axis = 1)

**Модуль каждого элемента массива:**

In [ ]:
a = np.array([-2, 3, -4])
print(np.abs(a)) # возвращает модуль того же типа, что и исходный массив
print(np.fabs(a)) # возвращает модуль типа float


**Объединение массивов:**

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))

In [ ]:
print(np.stack((a, b)))
print()
print(np.stack((a, b), axis = 1))

**Разделение массивов:**

In [ ]:
a = np.arange(5)
c = np.array_split(a, 3)
print(c[0])
print(c[1])
print(c[2])

**Другие действия с массивами:**

In [ ]:
# подсчет количества вхождений каждого элемента массива
a = np.array([0, 1, 2, 2, 1, 1, 3, 3, 3, 4]) 
np.bincount(a)

In [ ]:
a = np.random.randint(1, 10, 10) 
print(a)
np.argpartition(a, kth = 3) # сортирует kth-ый элемент массива, 
                            # значения меньше kth-ого элемента будут расположены слева от него, 
                            # а больше - справа в произвольном порядке. Функция возвращает ИНДЕКСЫ элементов.

In [ ]:
# удаление строк или столбцов матрицы
np.arange(4, 6, 1)
a = np.array([np.arange(3), np.arange(3,6)])
print(a, "\n")
print(np.delete(a, 1, axis = 1)) # удаление второго столбца
print()
print(np.delete(a, 0, axis = 0)) # удаление первой строки

# Задачи для самостоятельного решения  
---

**1. Создать одномерный массив, заполненный двойками, но 6-ой элемент равен 8**

In [79]:
a=np.full(10, 2)
a[6]=8
print(a)

[2 2 2 2 2 2 8 2 2 2]


**2. Создать одномерный массив, со значениями от 15 до 98**

In [15]:
a=np.arange(15, 99)
print(a)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62
 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86
 87 88 89 90 91 92 93 94 95 96 97 98]


**3. Перевернуть вектор  
*(123 -> 321)***

In [17]:
a=np.array([1,2,3])
a=np.flip(a)
print(a)

[3 2 1]


**4. Найти минимальный и максимальный элемент двумерного массива размерностью 15х15**

In [37]:
a=np.random.random((15, 15))
max=a[np.argmax(a)%15][int(np.argmax(a)/15)]
min=a[np.argmin(a)%15][int(np.argmin(a)/15)]
print(max,min)

0.5986133822022177 0.0003427831588739272


**5. Поменять в двумерном массиве 3 и 4 строку между собой**

In [56]:
a=np.arange(18).reshape((6,3))
print(a)
a[[3,4]]=a[[4,3]]
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [12 13 14]
 [ 9 10 11]
 [15 16 17]]


**6. Поменять каждый 4-ый элемент в одномерном массиве на заданное число: 212**

In [82]:
a=np.arange(24)
a[3::4] = 212
print(a)

[  0   1   2 212   4   5   6 212   8   9  10 212  12  13  14 212  16  17
  18 212  20  21  22 212]


**7. Используя циклы написать собственную реализацию умножения двух двумерных матриц, засечь время выполнения и сравнить его с функцией умножения матриц NumPy:**

In [12]:
n = 5
A = np.arange(n**2).reshape((n,n))
B = np.arange(n**2, 2 * n**2).reshape((n,n))

In [13]:
%%time
C = A @ B
print(C)

[[ 400  410  420  430  440]
 [1275 1310 1345 1380 1415]
 [2150 2210 2270 2330 2390]
 [3025 3110 3195 3280 3365]
 [3900 4010 4120 4230 4340]]
CPU times: total: 0 ns
Wall time: 0 ns


In [17]:
%%time
C = np.zeros((n, n))
for i in range(n):
     for j in range(n):
          for k in range(n):
                C[i,j] += A[i][k] * B[k][j]
print(C)

[[ 400.  410.  420.  430.  440.]
 [1275. 1310. 1345. 1380. 1415.]
 [2150. 2210. 2270. 2330. 2390.]
 [3025. 3110. 3195. 3280. 3365.]
 [3900. 4010. 4120. 4230. 4340.]]
CPU times: total: 0 ns
Wall time: 0 ns
